@include('layouts.header')
<section class="page-hero"><div class="container"><span class="page-kicker">Compliance Insights</span><h1>Clear guidance for changing AML obligations.</h1><p>Explore practical perspectives on UAE AML/CFT controls, customer due diligence, screening, reporting, governance, and regulatory readiness.</p></div></section>
<section class="content-section"><div class="container"><div class="section-header section-header--center"><span class="page-kicker">Explore</span><h2>Find the guidance relevant to your next decision.</h2></div><div class="row g-4">
<div class="col-lg-6"><article class="modern-card p-lg-5"><span class="modern-card__icon"><i class="bi bi-journal-text" aria-hidden="true"></i></span><h2 class="h3">Articles & Guides</h2><p>Practical explanations, frameworks, and implementation guidance for compliance teams and business leaders.</p><a href="{{ route('blog') }}" class="btn button-secondary mt-2">Browse Articles</a></article></div>
<div class="col-lg-6"><article class="modern-card p-lg-5"><span class="modern-card__icon"><i class="bi bi-megaphone" aria-hidden="true"></i></span><h2 class="h3">News & Updates</h2><p>Follow regulatory developments, important reminders, and updates from the compliance landscape.</p><a href="{{ route('news') }}" class="btn button-secondary mt-2">View News</a></article></div>
</div></div></section>
<section class="content-section content-section--soft"><div class="container"><div class="section-header"><span class="page-kicker">Core Topics</span><h2>Built around the work compliance teams perform.</h2></div><div class="row g-4">@foreach ([['person-vcard','KYC, CDD & EDD'],['shield-exclamation','Sanctions & PEP Screening'],['diagram-3','Risk Assessment'],['send-check','goAML & Reporting'],['people','Governance & Training'],['clipboard-check','Audit Readiness']] as [$icon,$title])<div class="col-6 col-lg-4"><div class="modern-card"><span class="modern-card__icon"><i class="bi bi-{{ $icon }}" aria-hidden="true"></i></span><h3>{{ $title }}</h3></div></div>@endforeach</div></div></section>
<section class="content-section"><div class="container"><div class="cta-band d-lg-flex align-items-center justify-content-between gap-4"><div><h2>Need advice specific to your organisation?</h2><p class="mb-lg-0">Use our insights as a starting point, then discuss your operating context with our team.</p></div><a href="{{ route('contact') }}" class="btn btn-light rounded-pill px-4 py-3">Talk to a Specialist</a></div></div></section>
@include('layouts.footer')
